# Generated by Django 6.0 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_user_cached_role_orgs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keycloak_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
