# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "__first__"),
        ("facility", "0485_rename_patientmobileotp_mobileotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.city",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="pincode",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
