# Generated by Django 6.0 on 2026-08-19 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0486_facility_catalog_location_and_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="features",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(
                    choices=[
                        (1, "CT Scan"),
                        (2, "Maternity Care"),
                        (3, "X-Ray"),
                        (4, "Neonatal Care"),
                        (5, "Operation Theater"),
                        (6, "Blood Bank"),
                        (7, "Emergency Services"),
                        (8, "Inpatient Services"),
                        (9, "Outpatient Services"),
                        (10, "Intensive Care Units (ICU)"),
                        (11, "Pharmacy"),
                        (12, "Rehabilitation Services"),
                        (13, "Home Care Services"),
                        (14, "Psychosocial Support"),
                        (15, "Respite Care"),
                        (16, "Daycare Programs"),
                    ]
                ),
                blank=True,
                null=True,
            ),
        ),
    ]
