# Generated by Django 6.0 on 2026-08-10 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    RF1 -- move recent views off Redis and into PostgreSQL.

    The table starts empty. Recent-view state that exists in Redis is
    deliberately **not** backfilled: it is ephemeral, non-critical user
    convenience state with no clinical or audit value, the deployment is
    greenfield, and a reader repopulates their own list by using the feature.
    Reading the old Redis lists would reintroduce, for one migration, exactly
    the dependency this change removes.
    """

    dependencies = [
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValueSetRecentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('display', models.TextField()),
                ('designation', models.JSONField(blank=True, default=None, null=True)),
                ('last_viewed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valueset_recent_views', to=settings.AUTH_USER_MODEL)),
                ('valueset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.valueset')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'valueset', '-last_viewed_at'], name='user_valueset_recent_view_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'valueset', 'code'), name='unique_user_valueset_recent_view_code')],
            },
        ),
    ]
