# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "__first__"),
        ("emr", "0081_recent_views_postgres"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_city_organizations",
                to="cities_light.city",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_country_organizations",
                to="cities_light.country",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_region_organizations",
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_subregion_organizations",
                to="cities_light.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="pincode",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
