# Generated by Django 6.0 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "__first__"),
        ("emr", "0082_organization_geographic_catalog_and_patient_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.city",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.subregion",
            ),
        ),
    ]
