# Generated by Django 6.0 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0083_patient_catalog_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="keycloak_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
