# Generated by Django 6.0 on 2026-09-07 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0084_patient_authentication_identities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('provider_id', models.CharField(db_index=True, max_length=32)),
                ('issuer', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='emr.patient')),
            ],
            options={
                'verbose_name': 'Patient External Identity',
                'verbose_name_plural': 'Patient External Identities',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('provider_id', 'issuer', 'subject'), name='unique_patient_external_identity')],
            },
        ),
    ]
